### ISSUE TITLE
Documentation Review

### ISSUE THREAD

**Issue by jmeyer90** [aahmed019/CampCentral#1]
# Home
1. Include a description of your site on the home page
2. Include links to your Wiki pages on the home page

# MVPs
1. Make sure to use full sentences and proper grammar in your documentation. This will be presented to recruiters and potential employers.
2. Reviews should be your 3rd or 4th MVP, after Splash/Authentication and creating a location's show page.
3. We're missing any mention of a location's show page
3. Splash/Authentication- List what parts of the site users cannot access unless logged in.
4. Every MVP needs more detail. Currently, we're looking at things from a very big picture perspective. We want to break these down into the items which are required for each MVP. Example: 
4) Search for camping areas (2 day)
        A user can search for camping spots
        Uses Google Maps to find the camping spots
Should be changes to
4) Search for camping areas (2 day)
       Users can search for camp sites based off ${insert categories}
       Camp sites will be displayed as index items with brief descriptions
       Users will be able to see camp sites rendered on Google Maps
       Users can use Google Maps to search for camp sites based off location.

# Schema
1. Include columns you will index on as bullet points under the respective table.
2. Include associations as bullet points under the respective table.

# Sample State
1. Populate the UI and errors slice of state with relevant data. Our UI slice of state will include a boolean value for if the page is currently loading, any modals we want to render, etc. Our errors slice of state will contain any errors we would want to display to the user.

# Back-End Routes
1. We won't need to edit a user's info for this project
2. Bookings:
    DELETE /api/user_id/bookings/:booking_id -> DELETE /api/bookings/:id
3. Locations (we'll use our current user to get the hostId):
    POST /api/host/id/locations -> POST /api/locations 
    PATCH /api/host/id/locations/:id -> PATCH /api/locations/:id 
    DELETE /api/host/id/locations/:id -> DELETE /api/locations/:id 

# Front-End Routes & Components
1. Beak down the components into their sub-components as well. Become very modular and think about what sub-components you'll need to create when building out your application.

**Comment by aahmed019** [comment]
I have made the following changes per your review:

1. Home page edits:
    * I've added small description
    * I've added hyper links for the wiki pages.
    
2. MVPs page edits:
    * Proper grammar has been added
    * Order of MVPs has been changed
    *  Added MVP for Locations (show page)
    * Added more detail to MVP list
    
3.  Schema edits:
    * Added bullet points of indexed columns and associations
 
4. Sample State edits:
    * Populated UI slice of state to include loading boolean state
    * added modal state for signup

5. Back-End Routes
    * Changed Booking DELETE route to match as there is no need to nest the route.
    * Changed location routes for similar reasons as DELETE.

6. Front-End Routes & Components
    * Broke down some components to base levels.

**Comment by jmeyer90** [comment]
Update on back-end routes:

REVIEWS:
- GET /api/locations/:location_id/reviews- gets the reviews for a location
- POST /api/locations/:location_id/reviews- Creates a review. We use our current_user as the author
- PATCH /api/reviews/:id - a user can update their review. We make sure the current_user is the author
- DELETE /api/reviews/:id - a user can delete their review. We make sure the current_user is the author

**Comment by jmeyer90** [comment]
All wIki documentation has been completed.

**Comment by jmeyer90** [comment]
All wIki documentation has been completed.
