### ISSUE TITLE
Reviews MVP

### ISSUE THREAD

**Issue by aahmed019** [aahmed019/CampCentral#10]
Hey Justin, my reviews MVP has full CRUD functionality and is ready for review.

**Comment by jmeyer90** [comment]
Reviews CRUD MVP-

* The input field for the review form should be  a text area.
* Style the textarea tag: padding, larger height.
* Style the edit review and delete review buttons to look like the form buttons

Optional Improvement: Reviews should have optional titles

**Comment by aahmed019** [comment]
* Changed input field to text area
* Styled review text area
* Styled edit and delete buttons to look like the form buttons

**Comment by aahmed019** [comment]
finished edits

**Comment by jmeyer90** [comment]
Everything looks great! Please move on to your next MVP.
