### ISSUE TITLE
Reservations

### ISSUE THREAD

**Issue by aahmed019** [aahmed019/CampCentral#12]
My reservations MVP is ready for review.

**Comment by jmeyer90** [comment]
Reservations CRUD MVP Review:

* Style edit form modal for a reservation to look like the reservation form on a Location show page 
* Clicking on a reservation in our reservations index page should bring us to the location's show page. 
* Continue styling the reservation index page. Consider including an image of the location in each reservation index item.

**Comment by aahmed019** [comment]
Added image to reservation, modal now looks like the form on the show page and clicking on the reservation takes a user to the show page.

**Comment by jmeyer90** [comment]
In the job search, continue styling the reservations index page. It currently looks a little empty with so much white space. However, feel free to continue on the the next MVP. This will be an item to work on once you've completed search and filter functionality.
